# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd510159efc2ba5cf3646b215ff14947fb87259b1cb88b123eec9efa148529f63db7c208b442a3a289bd1c5379ee9234ee9012d9ce9f2540b133f5fafabdcf16

test:
  secret_key_base: f4284f7d203d97a51e12ed386a20dad8c931c21cc8b3d2232019d5bcb8ea2341be3af74b4053cad93b24cf43b61afb0d6b80c11ef20be17e695f5383c0b0750c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
