# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ca91995b994ad975ddc9de687d77db011d9393708bbae6aa2e8b765aade8aaf90f39c0d85b00cd4061852b8a6bcd32e0154f4b02ba41c831cf29e00db7ba492

test:
  secret_key_base: 5856a333a2515b30dd5e8a4434b95441cc7145016e51148bd616ad8d6819b3c06985f6366162ff495cbd0a0e94c0bd79036656380c04a3daa11a0475c5eababd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
