require_relative 'piece'
require_relative 'pieces/stepping_piece'
require_relative 'pieces/sliding_piece'
require_relative "pieces/bishop"
require_relative "pieces/king"
require_relative "pieces/pawn"
require_relative "pieces/knight"
require_relative "pieces/queen"
require_relative "pieces/rook"
require_relative "invalid_move_error"
require_relative "invalid_user_input"
require_relative "check_error"
