# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e63efc40e445b8c245883962dad0de785905a9e8d0f8f7bb6a0a6d185fcea140d85c66ed60b68575bd0d7216cbaf7f284f7edfb852ad5230741059b63a949b6d

test:
  secret_key_base: 2239937e3cdf6fcf669d8f6d737ac5f65fc4a9caae07b226e444b219482370aba7548c8165abbccf7900677a25b72808b31dcdb0f71eb528be42e07e6ef93d97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
